### ISSUE TITLE
Unable to create a new release on GitHub

### ISSUE THREAD

**Issue by kostia** [jenslind/electron-release#9]
Hello,

when I try to create a release with `electron-release --app=VexEd.app --token=xxx`, I'm getting following message: `Error: Unable to create a new release on GitHub`.

If I inspect the releases page, I see that a release actually has been created, but it only contains the source code archives and the app is missing: https://github.com/kostia/VexEd/releases.

What am I doing wrong?
Thanks a lot!

**Comment by kostia** [comment]
I'm using version 2.1.1 with electron version 0.34.1.

**Comment by jenslind** [comment]
Yeah thats kind of hard to debug. I just released `2.1.2` which will hopefully log the error.

**Comment by kostia** [comment]
`Published new release to GitHub (v0.0.1)`, Yay!
Thanks a lot!
